name: Build and deploy

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]'
    workflow_dispatch:

jobs:
    build:
        name: Build and Deploy to Firebase
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup node version
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install dependencies
              run: npm ci
            - name: Build dependencies
              run: npm run build
              env:
                  NEXT_PUBLIC_SERVER_URL: https://ventaf.com
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions:app,hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
